frameworkVersion: "2"
service: lambda-fn-mhw
provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
  vpc:
    securityGroupIds:
      - sg-5d9e4215
    subnetIds:
      - subnet-f8067c9e
      - subnet-fc067eb5
  role: arn:aws:iam::665407732775:role/LambdaBasicExecution
  runtime: nodejs14.x
  region: sa-east-1
  stage: prod
  deploymentBucket:
    name: com.serverless.${self:provider.region}.functions
  timeout: 300
  memorySize: 2048
  versionFunctions: false
  # UNCOMMENT IF YOU NEED ENVIRONMENT VARIABLES
  environment:
    SERVER_ENV: production
functions:
  generate:
    image:
      name: appimage
      command:
        - index.generate
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http: PUT /generar
