frameworkVersion: "2"
service: lambda-fn-mhw-ref
provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
  vpc: none
  role: arn:aws:iam::665407732775:role/LambdaBasicExecution
  runtime: nodejs14.x
  region: sa-east-1
  stage: prod
  deploymentBucket:
    name: com.serverless.${self:provider.region}.functions.mhw
  versionFunctions: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: arn:aws:lambda:sa-east-1:665407732775:function:lambda-fn-mhw-refactoring-prod-generateRoutine
  environment:
    SERVER_ENV: production
    ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    DB_URI: ${env:DB_URI}
    DB_NAME: ${env:DB_NAME}
functions:
  generateRoutine:
    timeout: 900
    memorySize: 2048
    image:
      name: appimage
      command:
        - index.generateRoutine
      entryPoint:
        - '/lambda-entrypoint.sh'
  generate:
    timeout: 30
    memorySize: 512
    image:
      name: appimage
      command:
        - index.generate
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http: PUT /generate
  read:
    timeout: 30
    memorySize: 512
    image:
      name: appimage
      command:
        - index.read
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http: POST /read
