frameworkVersion: "2"
service: lambda-fn-mhw
provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
  vpc:
    securityGroupIds:
      - sg-5d9e4215
    subnetIds:
      - subnet-f8067c9e
      - subnet-fc067eb5
  role: arn:aws:iam::665407732775:role/LambdaBasicExecution
  runtime: nodejs14.x
  region: sa-east-1
  stage: prod
  deploymentBucket:
    name: com.serverless.${self:provider.region}.functions.mhw
  timeout: 30
  memorySize: 2048
  versionFunctions: true
  environment:
    SERVER_ENV: production
    DB_URI: mongodb+srv://josue:lospajaroscantanmientraslospecesnadan@heroku-28zqn5s2.htt13.mongodb.net/heroku_28zqn5s2?retryWrites=true&w=majority
    DB_NAME: heroku_28zqn5s2
functions:
  generate:
    image:
      name: appimage
      command:
        - index.generate
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http: PUT /generar
  read:
    image:
      name: appimage
      command:
        - index.read
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http: POST /read
