
name: CI

on:
  repository_dispatch:
    types: [ Deploy lambdas for MHWLib ]

  workflow_dispatch:
    inputs:
      project:
        description: Write in the input "deployment" to confirm
        required: true


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Config action 
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup AWS Core
        uses: aws-actions/setup-sam@v1
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: Setup NodeJs
        uses: actions/setup-node@v2
      - name: Deploy lambda to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_URI: ${{ secrets.DB_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "======================================================================="
          echo "Instaling serverless and setup credentials"
          pip3 install awscli
          npm config set prefix /usr/local
          npm install -g serverless@2.72.2
          aws ecr get-login-password --region sa-east-1 | docker login --username AWS  --password-stdin 665407732775.dkr.ecr.sa-east-1.amazonaws.com
          echo "======================================================================="
          echo "Start Deployment Lambda MHW"
          cd "${GITHUB_WORKSPACE}/"
          serverless deploy
          status=$?
          [ $status -eq 0 ] && echo "End Deployment Lambdas MHW" || exit 1
          exit 0
